# -*- coding: utf-8 -*-
"""AtividadeFunções

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yS52bK8wquAi6Eu7QV5powoKwlGzLuAU
"""

# 1

def imprimir_como_piramide (a):
    for i in range (1, a + 1):
        for j in range (i):
            print(i, end = "... ")
        print()
imprimir_como_piramide (10)

# 2

def retornar_fatorial (a):
    b = 1
    for i in range (1, a + 1):
        b *= i
    return b
print(retornar_fatorial (10))

# 3

def verificar_primo (a):
    if a == 1:
        return False
    elif a > 1:
        for i in range(2, a):
            if a % i == 0:
                return False
        return True
print("O número é primo." if verificar_primo (3) else "O número não é primo.")

# 4

def reverter_string (a):
    b = ""
    for i in range (len (a)):
        b += a [-(i + 1)]
    return b
print(reverter_string("Teste"))

# 5

def maior_valor(a):
  print(f"O valor maximo é: {max(a)}")

maior_valor([10, 20, 30, 40, 50])

# 6

def conta_vogais(string):
    vogais = "aeiouAEIOUáéíóú"
    contador = 0
    for char in string:
        if char in vogais:
            contador += 1
    return contador

texto = "Testando o código!"
print(conta_vogais(texto))

# 7

a = [1, 2, 3, 4, 5]
def somar_quadrados (a):
    b = 0
    for i in range (len (a)):
        b += a [i] ** 2
    return b
print(somar_quadrados (a))

# 8

def imprimir_tabuada (a):
    for i in range (1, 11):
        print(f"{a} X {i} = {a * i}")
imprimir_tabuada (5)
