# -*- coding: utf-8 -*-
"""Estruturas Sequenciais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2h4T4_4MZHo6GGK4RUVo86VkcKJ5AVx
"""

# Faça um programa que mostre a mensagem "Olá mundo" na tela.

print("Olá mundo")

# Faça um programa que peça um número e então mostre a mensagem.

number = int(input("Por favor, insira um número: "))
print(f"Você inseriu o número {number}.")

# Faça um programa que peça dois números e imprima a soma.

firstNumber = int(input("Por favor, insira um número: "))
secondNumber = int(input("Agora, outro: "))
print(f"A soma dos números que você inseriu é {firstNumber + secondNumber}")

# Faça um programa que peça as quatro notas de um bimestre e mostre a média dele.

averageNote = 0
for i in range(4):
        averageNote = averageNote + float(input(f"Insira a {i + 1}ºa nota: "))
print(f"A média é {averageNote / 4:.2}.")

# Faça um programa que converta metros para centímetros.

print(f"A distância em centímetros é: {(int(input('Insira uma distância em metros: ')) * 100)}")

# Faça um prograa que peça o raio de um círculo, calcule e mostre a área dele.

print(f"A área de um círculo que possua o raio inserido é (aproximadamente): {(float(input('Insira um raio de um círculo: ')) ** 2) * 3.14:.2f}")

# Faça um programa que calcule a área de um quadrado e, em seguida, mostre o dobro da área para o usuário.

print(f"A área de um quadrado cujos lados tenham esse comprimento é: {float(input('Por favor, insira o comprimento dos lados do quadrado: ')) ** 2}")

# Faça um programa que pergunte quanto o usuário ganha por hora e o número de horas trabalhadas por mês e, então, mostre o seu salário mensal.

salaryPerHour = float(input("Insira quando você ganha hora: "))
hoursPerMonth = float(input("Agora, quantas horas você trabalha por mês: "))
print(f"Seu salário é: {salaryPerHour * hoursPerMonth}")

# Faça um programa que peça uma temperatura em Fahrenheit e converta-a em Celsius.

print(f"Convertendo essa temperatura para Celsius: {(((float(input('Insira uma temperatura em Fahrenheit: ')) - 32) / 9) * 5):.2f}")
