# -*- coding: utf-8 -*-
"""Atividade - dicionários(07/03)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPJBdRe5xN7DV6vG6VMH-70VwgcmI4A7

1 - Faça um programa que possua um Dicionário, adicione elementos ao dicionário e os mostre na tela.
"""

equipe = {'integrante 1': 'Talita', 'Integrante 2': 'Helen', 'Integrante 3': 'Ilana'}

"""2 - Faça um programa, utilizando Dicionários, que peça para o usuário inserir o nome de três produtos de mercado e seus respectivos preços e os mostre na tela."""

a = (input(Insira um produto:)
precoa = (input(Insira o preço desse produto:)

b = (input(Insira um produto:)
precob = (input(Insira o preço desse produto:)

c = (input(Insira um produto:)
precoc = (input(Insira o preço desse produto:)

produtos: {'Produto 1': a, 'Preço do produto 1': 'precoa', 'Produto 2': b, 'Preço do produto 2': 'precob' 'Produto 3': c, 'Preço do produto 3': 'precoc'

"""3 - Faça um programa, utilizando Dicionários, que peça para o usuário inserir
 quatro notas e mostre na tela as notas e a média entre elas.
"""

notas = {}
soma = 0

for i in range(1, 5):
    nota = float(input(f"Digite a {i}ª nota: "))
    notas[f"Nota {i}"] = nota
    soma += nota

media = soma / 4

print("\nNotas inseridas:")
for key, value in notas.items():
    print(f"{key}: {value}")
print(f"Média: {media}")

"""4 - Faça um programa, utilizando Dicionários, que:  
    1° Passo: Peça para o usuário inserir quatro coisas em uma “Caixa Misteriosa”; 2° Passo: Peça para o usuário inserir um número; 3° Passo: Mostre na tela o que foi inserido na posição do número inserido pelo usuário.

"""

caixa_misteriosa = {}

for i in range(1,5):
    item = input(f"Digite uma coisa misteriosa: ")
    caixa_misteriosa[i] = item

num = int(input("Insira um número de 1 a 4 para revelar o que está na Caixa Misteriosa: "))
#tem que consultar com dicionário
print(f"Na posição {num} da Caixa Misteriosa, temos: {caixa_misteriosa[num]}")

"""5 - Faça um programa, utilizando Dicionários, que:
    1° Passo: Peça para o usuário inserir o nome de três funcionários e os
mostre na tela; 2° Passo: Peça para o usuário demitir um funcionário e mostre na tela os funcionários restantes.
"""

funcionarios = {}

for i in range(1, 4):
    nome = input(f"Digite o nome do {i}º funcionário: ")
    funcionarios[i] = nome

print("\nFuncionários inseridos:")
for chave, valor in funcionarios.items():
    print(f"{chave}: {valor}")

num_demissao = int(input("\nDigite o número do funcionário que deseja demitir: "))

if num_demissao in funcionarios:
    del funcionarios[num_demissao]
else:
    print("Funcionário não encontrado.")

print("\nFuncionários restantes:")
for chave, valor in funcionarios.items():
    print(f"{chave}: {valor}")