# -*- coding: utf-8 -*-
"""Atividade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytSAEJe1xr6P4b_LiFzC9uOl8BTnnEin
"""

# 1

note = float(input("Insira uma nota entre zero e dez: "))
while note < 0 or note > 10:
    note = float(input("Você inseriu uma nota que é ou menor do que zero ou maior do que dez, insira uma nota válida desta vez: "))

# 2

a = input("Insira seu nome de usuário: ")
b = input("Insira sua senha: ")
while a == b:
    print("Você inseriu uma senha que é igual ao nome de usuário.")
    a = input("Insira seu nome de usuário: ")
    b = input("Insira sua senha: ")

# 3.1

for i in range (1, 21):
    if i != 20:
        print(f"{i}, ")
    else:
        print(f"{i}.")

# 3.2

numbers = []
for i in range (1, 21):
    numbers.append(i)
print(numbers)

# 4

a = []
for i in range(5):
    a.append(int(input("Insira um número: ")))
print(f"O maior número entre os inseridos é: {max(a)}")

# 5

a = 0
for i in range (1, 6):
    a += int(input(f"Insira o valor {i}: "))
print(f"A soma dos números inseridos é {a}, sendo {a / 4} a sua média.")

# 6

a = []
b = []
c = 0
for i in range(5):
    a.append(int(input("Insira um número: ")))
    if a[i]%2 != 0:
        b.append(a[i])
        c += 1
print(f"{'O número ímpar inserido é:' if c == 1 else 'Os números ímpares inseridos são:'} {b}")

# 7

a = int(input("Insira um valor: "))
b = int(input("Insira outro (maior, distante no mínimo dois do primeiro): "))
while (b - a) < 2:
    print("É ideal que o segundo valor seja maior, distante dois números do primeiro.")
    a = int(input("Insira um valor: "))
    b = int(input("Insira outro (maior, distante no mínimo dois do primeiro): "))
for i in range(a + 1, b):
    print(f"{i} está entre os valores {a} e {b}.")

# 8

a = int(input("Insira um número para gerar sua tabuada: "))
print(f"A tabuda de {a}:")
for b in range(1, 11):
    print(f"{a} x {b} = {a * b}")

# 9

a = int(input("Insira o valor base: "))
b = int(input("Insira o valor expoente: "))
c = a
for i in range(b - 1):
    a *= a
print(f"{c} elevado a {b} é {a}.")

# 10

a = []
b = []
c = 0
d = []
e = 0
for i in range(10):
    a.append(int(input("Insira um número: ")))
    if a[i]%2 != 0:
        b.append(a[i])
        c += 1
    else:
        d.append(a[i])
        e += 1
if c > 0:
    print(f"{'O número ímpar inserido é:' if c == 1 else 'Os números ímpares inseridos são:'} {b}")
if e > 0:
    print(f"{'O número par inserido é:' if c == 1 else 'Os números pares inseridos são:'} {d}")

# 11

def serieDeFibonacci(n):
    serie = [1, 1]
    while len(serie) < n:
        serie.append(serie[-1] + serie[-2])
    return serie[:n]

print(f"Eis a série gerada até o n-ésimo termo: {serieDeFibonacci(int(input('Insira o valor do n-ésimo termo: ')))}")

# 12

serie = [1, 1]
while serie[-1] <= 500:
    serie.append(serie[-1] + serie[-2])
print(f"Eis a série gerada até que o valor seja maior do que 500: \n {serie} ")

# 13

a = int(input("Insira um valor: "))
b = a
for i in range(a - 1, 1, -1):
    print(f"{a} * {i} = {a * i}")
    a *= i
print(f"O valor {b} fatorado é {a}.")
